using Frends.PowerShell.RunScript.Definitions;
using System.ComponentModel;
using System.Diagnostics;
using System.Management.Automation;
using System.Management.Automation.Runspaces;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;
using System.Text;

[assembly: InternalsVisibleTo("Frends.PowerShell.RunScript.Tests")]
namespace Frends.PowerShell.RunScript;

/// <summary>
/// PowerShell task.
/// </summary>
public static class PowerShell
{
    /// For mem cleanup.
    static PowerShell()
    {
        var currentAssembly = Assembly.GetExecutingAssembly();
        var currentContext = AssemblyLoadContext.GetLoadContext(currentAssembly);
        if (currentContext != null)
            currentContext.Unloading += OnPluginUnloadingRequested;
    }

    /// <summary>
    /// Executes a PowerShell script from a file or the script parameter.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.PowerShell.RunScript)
    /// </summary>
    /// <param name="input">Input parameters</param>
    /// <param name="options">Option parameters</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { Result: List&lt;dynamic&gt;, Errors: List&lt;string&gt;, Log: string}</returns>
    public static PowerShellResult RunScript(RunScriptInput input, [Browsable(false)] RunOptions options, CancellationToken cancellationToken)
    {
        return DoAndHandleSession(options?.Session, session =>
        {
            var script = input.ReadFromFile ? File.ReadAllText(input.ScriptFilePath) : input.Script;
            var tempScript = Path.Combine(Path.GetTempPath(), $"{Path.GetRandomFileName()}.ps1");

            try
            {
                File.WriteAllText(tempScript, script, Encoding.UTF8);
                if (input.ExecuteNativeShell)
                return ExecuteProcess(tempScript, input.Parameters);
                else 
                return ExecuteCommand(tempScript, input.Parameters, input.LogInformationStream, session.PowerShell, cancellationToken);
            }
            finally
            {
                File.Delete(tempScript);
            }
        });
    }

    private static PowerShellResult ExecuteProcess(string scriptPath, PowerShellParameter[] parameters){
        List<dynamic> results = new();
        List<string> errors = new();

        string parameterString = string.Empty;
        if (parameters != null)
        {
            foreach (var param in parameters)
            {
                parameterString += $"-{param.Name} \"{param.Value}\" ";
            }
        }

        using Process process = new();
        process.StartInfo = new()
        {
            FileName = "powershell.exe",
            Arguments = $"-NoProfile -ExecutionPolicy Bypass -File \"{scriptPath}\" {parameterString}",
            UseShellExecute = false,CreateNoWindow = true,
            RedirectStandardError = true,
            RedirectStandardOutput = true,
        };

        process.OutputDataReceived += (sender, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.Data))
                results.Add(args.Data);
        };

        process.ErrorDataReceived += (sender, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.Data))
                errors.Add(args.Data);
        };

        try
        {
            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();
            process.WaitForExit();
        }
        catch (Exception ex)
        {
            errors.Add($"Exception occurred while running the script: {ex.Message}");
        }
        finally
        {
            process.Close();
        }

        return new PowerShellResult(results, errors, string.Empty);

    }

    private static PowerShellResult ExecuteCommand(string inputCommand, PowerShellParameter[] powerShellParameters, bool logInformationStream, System.Management.Automation.PowerShell powershell, CancellationToken cancellationToken)
    {
        var command = new Command(inputCommand, isScript: false, useLocalScope: false);

        foreach (var parameter in powerShellParameters ?? Array.Empty<PowerShellParameter>())
        {
            cancellationToken.ThrowIfCancellationRequested();
            var parameterName = parameter.Name.Trim('-', ' '); // Remove dash from start

            // Switch parameters will have to specify value as true:
            command.Parameters.Add(new CommandParameter(parameterName, parameter.Value));
        }

        powershell.Commands.AddCommand(command);
        return ExecutePowershell(powershell, logInformationStream);
    }

    private static PowerShellResult DoAndHandleSession(SessionWrapper sessionFromOutside, Func<SessionWrapper, PowerShellResult> action)
    {
        SessionWrapper internalSession = null;
        // use the external session if provided or create and dispose an internal session
        var session = sessionFromOutside ?? (internalSession = CreateSession());

        try
        {
            return action.Invoke(session);
        }
        finally
        {
            internalSession?.Dispose();
        }
    }

    internal static SessionWrapper CreateSession()
    {
        // Leave this internal for now, turn public to support shared sessions between task executions
        return new SessionWrapper();
    }

    private static PowerShellResult ExecutePowershell(System.Management.Automation.PowerShell powershell, bool logInformationStream)
    {
        try
        {
            var execution = powershell.Invoke();
            var result = new PowerShellResult
            (
                // Powershell return values are usually wrapped inside of a powershell object, unwrap it or if it does not have a baseObject, return the actual object
                execution?.Select(GetResultObject).ToList(),
                GetErrorMessages(powershell.Streams.Error),
                logInformationStream == false ? "" : string.Join("\n", powershell.Streams.Information.Select(info => info.MessageData.ToString()))
            );

            return result;
        }
        catch (Exception e)
        {
            throw new Exception($"Encountered terminating error while executing powershell: \n{e}\nErrors:\n{string.Join("\n", GetErrorMessages(powershell.Streams.Error))}");
        }
        finally
        {
            powershell.Commands.Clear(); // Clear the executed commands from the session so they do not get executed again
            powershell.Streams.ClearStreams();
        }
    }

    private static IList<string> GetErrorMessages(PSDataCollection<ErrorRecord> errors)
    {
        return errors.Select(err => $"{err.ScriptStackTrace}: {err.Exception.Message}").ToList();
    }

    private static object GetResultObject(PSObject result)
    {
        if (result?.BaseObject == null || result.BaseObject is PSCustomObject)
            return result;

        return result.BaseObject;
    }

    /// <summary>
    /// Executes a PowerShell command with parameters, leave parameter value empty for a switch.
    /// This method is for testing and to enable running scripts on device.
    /// </summary>
    public static PowerShellResult RunCommand(string command, PowerShellParameter[] parameters, [Browsable(false)] RunOptions options, CancellationToken cancellationToken)
    {
        return DoAndHandleSession(options?.Session, (session) =>
        {
            return ExecuteCommand(command, parameters, false, session.PowerShell, cancellationToken: cancellationToken);
        });
    }

    private static void OnPluginUnloadingRequested(AssemblyLoadContext obj)
    {
        obj.Unloading -= OnPluginUnloadingRequested;
    }
}