name: Frends.PowerShell.RunCommand Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.PowerShell.RunCommand/**'
      - '.github/workflows/RunCommand*.yml'
  workflow_dispatch:

jobs:
  work_push:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/official_task_pipeline.yml@main
    with:
      workflow_mode: work
      os: all
      workdir: Frends.PowerShell.RunCommand
      strict_analyzers: 'false'
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      target_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
