name: Frends.PowerShell.RunCommand Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.PowerShell.RunCommand/**'
  workflow_dispatch:
    paths:
      - 'Frends.PowerShell.RunCommand/**'
  
jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.PowerShell.RunCommand
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}